name: Deploy to GoDaddy via SFTP

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local_path: "./*"
          remote_path: ${{ secrets.SFTP_TARGET }}
          sftp_only: true
          delete_remote_files: false
